[package]
name = "webp_convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webp = "0.2"
image = "0.24.0"
rocket = "=0.5.0-rc.3"